### ISSUE TITLE
Recommendations for updating Python example doc and patching bugs.

### ISSUE THREAD

**Issue by techandy42** [HammingHQ/hamming-examples#6]
Hello. I ran the experiments, and I would like to mention a couple of things about the setup process.

1. Python versions below 3.10.4 run into the "ImportError: cannot import name 'TypeAlias' from 'typing'" issue, which can be fixed using a Conda environment with Python version 3.10.4.
```
conda create --name hammingai python=3.10.4
conda activate hammingai
pip install -r requirements.txt
```
2. There was a rename in the file; now the command should be `python3 sample_dataset/main.py` instead of `python3 sample_dataset/create.py` and `python3 single_retrieval_rag/main.py` instead of `python3 single_retrieval_rag/run.py`.
3. There is an f-string error on line 42 of `single_retrieval_rag/main.py`, it should be `print(f"Running query: {input['query']}")` instead of `print(f"Running query: {input["query"]}")`.

**Comment by sumanyu** [comment]
Thanks @techandy42; what python version were you using?

**Comment by techandy42** [comment]
I was initially using Python 3.8 which didn't work, so I switched to Python 3.10.4 with Conda. I also tried Python 3.9 on Conda but the same error occurred.
